"use server"

import { revalidatePath } from "next/cache"
import { createClient } from "@/lib/supabase/server"
import { orderSchema, type OrderFormData } from "@/lib/validators/order"

export async function getOrders(filters?: {
  status?: string
  priority?: string
  search?: string
}) {
  const supabase = await createClient()
  let query = supabase
    .from("orders")
    .select("*, buyer:buyers(id, name, company)")
    .order("created_at", { ascending: false })

  if (filters?.status) {
    query = query.eq("status", filters.status)
  }
  if (filters?.priority) {
    query = query.eq("priority", filters.priority)
  }
  if (filters?.search) {
    const escaped = filters.search.replace(/%/g, "\\%").replace(/_/g, "\\_")
    query = query.or(`order_number.ilike.%${escaped}%,style_name.ilike.%${escaped}%`)
  }

  const { data, error } = await query
  if (error) throw new Error(error.message)
  return data
}

export async function getOrder(id: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("orders")
    .select("*, buyer:buyers(*), order_items(*)")
    .eq("id", id)
    .single()

  if (error) throw new Error(error.message)
  return data
}

const VALID_ORDER_STATUSES = ["draft", "confirmed", "in_production", "completed", "dispatched", "cancelled"] as const

export async function createOrder(formData: OrderFormData) {
  const validated = orderSchema.parse(formData)
  const supabase = await createClient()

  // Finding #2 — require authentication on all mutations
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { items, ...orderData } = validated

  // Clean empty strings to null
  const cleaned = Object.fromEntries(
    Object.entries(orderData).map(([k, v]) => [k, v === "" ? null : v])
  ) as Record<string, unknown>

  // Insert order (order_number auto-generated by trigger)
  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      ...cleaned,
      order_number: "", // trigger will set this
    })
    .select()
    .single()

  if (orderError) return { error: orderError.message }

  // Insert order items
  const orderItems = items.map((item) => ({
    order_id: order.id,
    size: item.size,
    color: item.color,
    quantity: item.quantity,
    unit_price: item.unit_price,
  }))

  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(orderItems)

  if (itemsError) {
    // Rollback: delete the order if items fail
    await supabase.from("orders").delete().eq("id", order.id)
    return { error: itemsError.message }
  }

  revalidatePath("/orders")
  revalidatePath("/")
  return { data: order }
}

export async function updateOrder(id: string, formData: OrderFormData) {
  const validated = orderSchema.parse(formData)
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { items, ...orderData } = validated

  const cleaned = Object.fromEntries(
    Object.entries(orderData).map(([k, v]) => [k, v === "" ? null : v])
  )

  // Update order
  const { error: orderError } = await supabase
    .from("orders")
    .update(cleaned)
    .eq("id", id)

  if (orderError) return { error: orderError.message }

  // Replace order items: delete existing, insert new
  const { error: deleteError } = await supabase
    .from("order_items")
    .delete()
    .eq("order_id", id)

  if (deleteError) return { error: deleteError.message }

  const orderItems = items.map((item) => ({
    order_id: id,
    size: item.size,
    color: item.color,
    quantity: item.quantity,
    unit_price: item.unit_price,
  }))

  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(orderItems)

  if (itemsError) return { error: itemsError.message }

  revalidatePath("/orders")
  revalidatePath(`/orders/${id}`)
  revalidatePath("/")
  return { success: true }
}

export async function updateOrderStatus(id: string, status: string) {
  // Finding #11 — validate status against allowlist to prevent arbitrary writes
  if (!VALID_ORDER_STATUSES.includes(status as typeof VALID_ORDER_STATUSES[number])) {
    return { error: "Invalid status" }
  }

  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { error } = await supabase
    .from("orders")
    .update({ status })
    .eq("id", id)

  if (error) return { error: error.message }

  revalidatePath("/orders")
  revalidatePath(`/orders/${id}`)
  revalidatePath("/")
  return { success: true }
}

export async function deleteOrder(id: string) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { error } = await supabase.from("orders").delete().eq("id", id)

  if (error) return { error: error.message }

  revalidatePath("/orders")
  revalidatePath("/")
  return { success: true }
}
