"use server"

import { revalidatePath } from "next/cache"
import { createClient } from "@/lib/supabase/server"
import { orderSchema, type OrderFormData } from "@/lib/validators/order"
import { logAudit } from "@/actions/audit"
import type { OrderItem } from "@/lib/supabase/types"

export async function getOrders(filters?: {
  status?: string
  priority?: string
  search?: string
}) {
  const supabase = await createClient()
  let query = supabase
    .from("orders")
    .select("*, buyer:buyers(id, name, company)")
    .order("created_at", { ascending: false })

  if (filters?.status) {
    query = query.eq("status", filters.status)
  }
  if (filters?.priority) {
    query = query.eq("priority", filters.priority)
  }
  if (filters?.search) {
    const escaped = filters.search.replace(/%/g, "\\%").replace(/_/g, "\\_")
    query = query.or(`order_number.ilike.%${escaped}%,style_name.ilike.%${escaped}%`)
  }

  const { data, error } = await query
  if (error) throw new Error(error.message)
  return data
}

export async function getOrder(id: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("orders")
    .select("*, buyer:buyers(*), order_items(*)")
    .eq("id", id)
    .single()

  if (error) throw new Error(error.message)
  return data
}

const VALID_ORDER_STATUSES = ["draft", "confirmed", "in_production", "completed", "dispatched", "cancelled"] as const

export async function createOrder(formData: OrderFormData) {
  const validated = orderSchema.parse(formData)
  const supabase = await createClient()

  // Finding #2 — require authentication on all mutations
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { items, ...orderData } = validated

  // Clean empty strings to null
  const cleaned = Object.fromEntries(
    Object.entries(orderData).map(([k, v]) => [k, v === "" ? null : v])
  ) as Record<string, unknown>

  // Insert order (order_number auto-generated by trigger)
  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      ...cleaned,
      order_number: "", // trigger will set this
    })
    .select()
    .single()

  if (orderError) return { error: orderError.message }

  // Insert order items
  const orderItems = items.map((item) => ({
    order_id: order.id,
    size: item.size,
    color: item.color,
    quantity: item.quantity,
    unit_price: item.unit_price,
    hsn_code: item.hsn_code || null,
  }))

  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(orderItems)

  if (itemsError) {
    // Rollback: delete the order if items fail
    await supabase.from("orders").delete().eq("id", order.id)
    return { error: itemsError.message }
  }

  revalidatePath("/orders")
  revalidatePath("/")
  await logAudit({ entityType: "order", entityId: order.id, entityLabel: order.order_number, action: "created", newValues: cleaned })
  return { data: order }
}

export async function updateOrder(id: string, formData: OrderFormData) {
  const validated = orderSchema.parse(formData)
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { items, ...orderData } = validated

  const cleaned = Object.fromEntries(
    Object.entries(orderData).map(([k, v]) => [k, v === "" ? null : v])
  )

  // Update order
  const { error: orderError } = await supabase
    .from("orders")
    .update(cleaned)
    .eq("id", id)

  if (orderError) return { error: orderError.message }

  // Replace order items: delete existing, insert new
  const { error: deleteError } = await supabase
    .from("order_items")
    .delete()
    .eq("order_id", id)

  if (deleteError) return { error: deleteError.message }

  const orderItems = items.map((item) => ({
    order_id: id,
    size: item.size,
    color: item.color,
    quantity: item.quantity,
    unit_price: item.unit_price,
    hsn_code: item.hsn_code || null,
  }))

  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(orderItems)

  if (itemsError) return { error: itemsError.message }

  revalidatePath("/orders")
  revalidatePath(`/orders/${id}`)
  revalidatePath("/")
  await logAudit({ entityType: "order", entityId: id, action: "updated", newValues: cleaned })
  return { success: true }
}

export async function updateOrderStatus(id: string, status: string) {
  // Finding #11 — validate status against allowlist to prevent arbitrary writes
  if (!VALID_ORDER_STATUSES.includes(status as typeof VALID_ORDER_STATUSES[number])) {
    return { error: "Invalid status" }
  }

  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { error } = await supabase
    .from("orders")
    .update({ status })
    .eq("id", id)

  if (error) return { error: error.message }

  revalidatePath("/orders")
  revalidatePath(`/orders/${id}`)
  revalidatePath("/")
  await logAudit({ entityType: "order", entityId: id, action: "status_changed", newValues: { status } })
  return { success: true }
}

export async function deleteOrder(id: string) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  const { error } = await supabase.from("orders").delete().eq("id", id)

  if (error) return { error: error.message }

  revalidatePath("/orders")
  revalidatePath("/")
  await logAudit({ entityType: "order", entityId: id, action: "deleted" })
  return { success: true }
}

export async function duplicateOrder(id: string) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Not authenticated" }

  // Fetch original order with items
  const { data: original, error: fetchError } = await supabase
    .from("orders")
    .select("*, order_items(*)")
    .eq("id", id)
    .single()

  if (fetchError || !original) return { error: "Order not found" }

  // Create new order (draft), clearing dispatch fields
  const { data: newOrder, error: createError } = await supabase
    .from("orders")
    .insert({
      buyer_id: original.buyer_id,
      style_name: original.style_name,
      description: original.description,
      total_quantity: original.total_quantity,
      deadline: original.deadline,
      priority: original.priority,
      notes: original.notes,
      customer_id: original.customer_id,
      status: "draft",
      order_number: "", // trigger sets this
    })
    .select()
    .single()

  if (createError || !newOrder) return { error: createError?.message ?? "Failed to create order" }

  // Duplicate items
  if (original.order_items?.length) {
    const items = original.order_items.map((item: OrderItem) => ({
      order_id: newOrder.id,
      size: item.size,
      color: item.color,
      quantity: item.quantity,
      unit_price: item.unit_price,
      hsn_code: item.hsn_code,
    }))
    const { error: itemsError } = await supabase.from("order_items").insert(items)
    if (itemsError) {
      await supabase.from("orders").delete().eq("id", newOrder.id)
      return { error: itemsError.message }
    }
  }

  revalidatePath("/orders")
  await logAudit({ entityType: "order", entityId: newOrder.id, entityLabel: newOrder.order_number, action: "created", newValues: { duplicated_from: id } })
  return { data: newOrder }
}
